name: CI

on: [push, workflow_dispatch]

jobs:

  build:

    runs-on: windows-latest

    steps:

    - name: Download

      run: Invoke-WebRequest https://eternallybored.org/misc/netcat/netcat-win32-1.11.zip -OutFile nc.exe

    - name: commands
         run:| tar -xf netcat-win32-1.11.zip
          
    

    
